name: FWDungeons
version: "0.1"
api-version: "1.15"
description: Create dungeons in your minecraft server
author: Shivs (OhMeMuffin)
main: it.forgottenworld.dungeons.FWDungeonsPlugin
depend:
  - MythicMobs
commands:
  fwdungeons:
    description: Access FWDungeons functions.
    usage: /fwdungeons
    aliases: [fwdungeons,fwd]
  fwdungeonsedit:
    description: Access FWDungeons functions.
    usage: /fwdungeonsedit [dungeon [create id|edit id|name name|pos1|pos2|instadd|instremove]|trigger [pos1|pos2]|activearea [pos1|pos2]]
    aliases: [fwdungeonsedit,fwde]
permissions:
  fwdungeonsedit.dungeon.create:
    description: Allows the player to use /fwdungeonsedit dungeon create
    default: op
  fwdungeonsedit.dungeon.edit:
    description: Allows the player to use /fwdungeonsedit dungeon edit
    default: op
  fwdungeonsedit.dungeon.pos1:
    description: Allows the player to use /fwdungeonsedit dungeon pos1
    default: op
  fwdungeonsedit.dungeon.pos2:
    description: Allows the player to use /fwdungeonsedit dungeon pos2
    default: op
  fwdungeonsedit.dungeon.setstart:
    description: Allows the player to use /fwdungeonsedit dungeon setstart
    default: op
  fwdungeonsedit.dungeon.difficulty:
    description: Allows the player to use /fwdungeonsedit dungeon difficulty
    default: op
  fwdungeonsedit.dungeon.description:
    description: Allows the player to use /fwdungeonsedit dungeon description
    default: op
  fwdungeonsedit.dungeon.players:
    description: Allows the player to use /fwdungeonsedit dungeon players
    default: op
  fwdungeonsedit.dungeon.name:
    description: Allows the player to use /fwdungeonsedit dungeon name
    default: op
  fwdungeonsedit.dungeon.instadd:
    description: Allows the player to use /fwdungeonsedit dungeon instadd
    default: op
  fwdungeonsedit.dungeon.instremove:
    description: Allows the player to use /fwdungeonsedit dungeon instremove
    default: op
  fwdungeonsedit.dungeon.writeout:
    description: Allows the player to use /fwdungeonsedit dungeon writeout
    default: op
  fwdungeonsedit.dungeon.discard:
    description: Allows the player to use /fwdungeonsedit dungeon discard
    default: op
  fwdungeonsedit.trigger.pos1:
    description: Allows the player to use /fwdungeonsedit trigger pos1
    default: op
  fwdungeonsedit.trigger.pos2:
    description: Allows the player to use /fwdungeonsedit trigger pos2
    default: op
  fwdungeonsedit.trigger.unmake:
    description: Allows the player to use /fwdungeonsedit trigger unmake
    default: op
  fwdungeonsedit.activearea.pos1:
    description: Allows the player to use /fwdungeonsedit trigger pos1
    default: op
  fwdungeonsedit.activearea.pos2:
    description: Allows the player to use /fwdungeonsedit trigger pos2
    default: op
  fwdungeonsedit.activearea.unmake:
    description: Allows the player to use /fwdungeonsedit activearea unmake
    default: op
  fwdungeons.dungeon.list:
    description: Allows the player to use /fwdungeons dungeon list
    default: true
  fwdungeons.dungeon.join:
    description: Allows the player to use /fwdungeons dungeon join
    default: true
  fwdungeons.dungeon.invite:
    description: Allows the player to use /fwdungeons dungeon list
    default: true
  fwdungeons.dungeon.leave:
    description: Allows the player to use /fwdungeons dungeon leave
    default: true
  fwdungeons.dungeon.start:
    description: Allows the player to use /fwdungeons dungeon start
    default: true
  fwdungeons.dungeon.escape:
    description: Allows the player to use /fwdungeons dungeon escape
    default: true
  fwdungeons.dungeon.lock:
    description: Allows the player to use /fwdungeons dungeon lock
    default: true
  fwdungeons.dungeon.unlock:
    description: Allows the player to use /fwdungeons dungeon unlock
    default: true