name: FWDungeons
version: "0.1"
description: Create dungeons in your minecraft server
main: it.forgottenworld.dungeons.FWDungeonsPlugin
commands:
  fwdungeons:
    description: Access FWDungeons functions.
    usage: /fwdungeons
    aliases: [fwdungeons,fwd]
permissions:
  fwdungeons.command:
    description: Allows the player to use /fwdungeons
    default: op